name: Publish to PyPI

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+rc[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+dev[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/bcrpy
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build the package
        run: python -m build

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__  # PyPI username for API token
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  # Store this in GitHub secrets
        run: python -m twine upload dist/*

